### ISSUE TITLE
Tests for CI

### ISSUE THREAD

**Issue by kamikazechaser** [kamikazechaser/tg-resolve#4]

**Comment by GochoMugo** [comment]
This should simple. Just resolve your username and compare the returned ID with your actual user ID. We might also ensure the result from the API contains all the expected props!

**Comment by kamikazechaser** [comment]
Seems great,should we use Mocha?

**Comment by GochoMugo** [comment]
Sounds good to me!

**Comment by GochoMugo** [comment]
you will work on this?
